export default [
  'INDIA',
  'United States of America',
  'United Kingdom',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Australia',
  'Austria',
  'Canada',
  'Finland',
  'Guatemala',
  'Guinea-Bissau',
  'Japan',
  'Israel',
  'Ireland',
  'New Zealand',
  'Philippines',
  'Saudi Arabia',
  'Suriname',
  'United Arab Emirates',
  'Zimbabwe',
  'Russia',
];
